# Generated by Django 4.2.30 on 2026-05-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_download_history'),
        ('searchapp', '0006_arrwebhookevent_extra_fields'),
    ]

    operations = [
    ]
